### ISSUE TITLE
很多控制器用的单列，更换账号后 ，单列没被销毁！

### ISSUE THREAD

**Issue by kangtian** [tbl00c/TLChat#11]
很多控制器用的单列，更换账号后 ，单列没被销毁，导致的结果是 第二个用户登陆了第一个用户的资料

**Comment by kangtian** [comment]
输入框  切换着很容易消失

**Comment by tbl00c** [comment]
输入框消失这个问题，你是用的模拟器测试的吗？如果模拟器的话，需要显示虚拟键盘。

**Comment by tbl00c** [comment]
单例这个，设计上的问题，需要根据实际业务场景去做改变
