### ISSUE TITLE
表情这一块非常不错，希望完善朋友圈

### ISSUE THREAD

**Issue by heyehao2008** [tbl00c/TLChat#4]
看过很过的朋友圈布局。都不是很流畅。看看作者有没有什么新思路。看作者的朋友圈界面。评论是打算cell里面嵌套tableView来做

**Comment by tbl00c** [comment]
对，当时的思路是这样。将朋友圈的cell分为两部分，第一部分是内容（文字，图片，链接等），第二部分是点赞和回复，第二部分用tableView实现，每一个评论又是一个cell。至于流畅性，我的考虑是朋友圈界面上不会存在太多的cell，cell内部的tableView只响应点击事件，通过合理的复用是可以保证流畅性的。
